### ISSUE TITLE
Coordinate Parsing Fails when >= MaxSignificandDigits

### ISSUE THREAD

**Issue by thenadz** [samcragg/sharpkml#14]
For example, parsing "-**101**.037559997352005,33.397169999458697" results in a point with the values "-**10.1**037559997352005,33.397169999458697".

I'm working on understanding the parsing logic -- if I get there before someone familiar with the codebase does I'll put in a PR. I suspect this was introduced with the recent changes to coordinate parsing logic, though I haven't confirmed whether the issue was still present prior to those changes yet.

**EDIT: Confirmed this was introduced in 4.0**

**Comment by samcragg** [comment]
Thanks for reporting this and sorry for breaking things.

I've reproduced the bug in a unit test so will get a fix out over the next couple of days.

**Comment by samcragg** [comment]
That should be fixed now in 4.0.1 (it's just been uploaded to NuGet so give it an hour)

Thanks for reporting and feel free to open the issue again if its still not working.

**Comment by thenadz** [comment]
Thanks! That did the trick.
