### ISSUE TITLE
Support gx:drawOrder on any geometry type

### ISSUE THREAD

**Issue by yskific** [samcragg/sharpkml#19]
Hi there,

Is there a way to extend GXDrawOrder property on all types derived from Geometry ?
[link](https://code.google.com/archive/p/kml-samples/issues/423)

Thanks

**Comment by samcragg** [comment]
Looking at the [latest documentation](https://developers.google.com/kml/documentation/kmlreference#gxdraworder), I still can only see it on the `LineString` type, so I don't think it's something that the library will support out of the box.

However, if you wanted to add support for any other `Geometry` type, then you might be able to do something like the [FeatureExtension](https://github.com/samcragg/sharpkml/blob/master/Examples/ExtendKml.cs) from the examples, e.g. to add it to the `Point` type 

``` C#
[KmlElement("drawOrder", KmlNamespaces.GX22Namespace)]
public class PointExtension : Element
{
    public int? Value
    {
        get
        {
            if (int.TryParse(this.InnerText, out int value))
            {
                return value;
            }
            else
            {
                return null;
            }
        }

        set
        {
            this.ClearInnerText();
            this.AddInnerText(value.ToString());
        }
    }
}

// Somewhere in your main function
KmlFactory.RegisterExtension<Point, PointExtension>();
```

This would allow you to add a `PointExtension` to the `Point` class, via it's `AddChild` method. To simplify this, I'd use a couple of extension methods:

``` C#
public static class PointExtensions
{
    public static int? DrawOrder(this Point point)
    {
        return point.Children
            .OfType<PointExtension>()
            .FirstOrDefault()
            ?.Value;
    }

    public static void DrawOrder(this Point point, int value)
    {
        PointExtension extension =
            point.Children
                    .OfType<PointExtension>()
                    .FirstOrDefault();

        if (extension == null)
        {
            extension = new PointExtension();
            point.AddChild(extension);
        }

        extension.Value = value;
    }
}
```

Usage would then be relativly simple:

```C#
var point = new Point
{
    Id = "point123",
    AltitudeMode = AltitudeMode.Absolute,
};
point.DrawOrder(123);
```

Hope that helps and gets you going in the right direction.

**Comment by yskific** [comment]
Thanks for your answer.
Even if not documented, if you give geometries a draworder google earth will render it correctly between various ClampedToGround geometries.
There is a difference between the stand-alone and the Online version of GE.
The stand-alone will order Linestring and Polygon type geometries separatly, and you can't be sure to get a the correct order between a LineString and a Polygon. The Online version seems to order all geometries globaly.

**Comment by samcragg** [comment]
Seeing how the behaviour is not documented and differs between different versions of GE, I don't think it's a feature that can be added to the library (as it will open up questions about it not working correctly).

Thanks for the suggestion though, I hope the workaround code is useful and lets you get closer to achieving your requirements.
