### ISSUE TITLE
Support for legacy KML/KMZ

### ISSUE THREAD

**Issue by bradh** [samcragg/sharpkml#2]
I note that the scope is OGC KML 2.2, but that there is some older stuff floating around that uses the 
`<kml xmlns="http://earth.google.com/kml/2.2">`
namespace.

I haven't done a close comparison, but is it likely a patch for support for that (basically treating it as a synonym for the OGC namespace) potentially be acceptable? 

The usual [legacy approach](https://github.com/samcragg/sharpkml/blob/master/docs/Legacy%20Files.md) doesn't really work so well for KMZ files.

**Comment by samcragg** [comment]
Could you use the [ReadKml](https://github.com/samcragg/sharpkml/blob/9271bda398554024a0b093d94d492771883dc6ad/SharpKml/Engine/KmzFile.cs#L273) method to get the string to pass to read legacy file?

Granted, it's a bit awkward, a better approach would be to have an options class that we can pass into the Open/Load methods.

**Comment by XPav** [comment]
I have some KML files, output from a random application, that had ```xmlns="http://earth.google.com/kml/2.1"```.  I am ashamed to say I did a text search/replace to Kml22Namespace before passing it to SharpKML.

**Comment by samcragg** [comment]
As there's been no suggestions made for a while, I'm closing this issue.

Feel free to submit another issue/PR if you think that library can be extended to make it easier.
