### ISSUE TITLE
How to replace a elements in a KML file?

### ISSUE THREAD

**Issue by vividos** [samcragg/sharpkml#20]
I'd like to use SharpKml to scan a kml file for `NetworkLink` elements and replace them with their (current) downloadable content. For this I check all elements (using `kml.Root.Flatten()` if they are `NetworkLink` elements, get their URL and download the kml content. I parse that text and get another KmlFile object. Then I generate a new `Folder` object, clone and copy all features from the loaded KmlFile's Document in that new folder and try to replace the `NetworkLink` with that. I couldn't figure out that last part, though. My code looks mostly like this:
```
Kml insertKml = LoadKmlFromText(kmlToInsert);
var doc = insertKml.Feature as Document;

var folder = new Folder
{
    Name = doc.Name
};

foreach (var featureToInsert in doc.Features)
    folder.AddFeature(featureToInsert.Clone());

networkLink.Parent.AddChild(folder);
networkLink.Parent.RemoveChild(networkLink);
```

How is that supposed to work? Is it possible at all? Thanks!

**Comment by samcragg** [comment]
It looks like you're on the right path. Since the parent of the `NetworkLink` is a `Container`, you might be best using the methods on that type:

```C#
var container = (Container)networkLink.Parent;
container.AddFeature(folder);
container.RemoveFeature(networkLink.Id)
```

Hope that helps

**Comment by vividos** [comment]
Thanks, that worked! I had to check if it's really a Container or the Kml element (when the NetworkLink is the only and topmost element), but that works. I also had to do a workaround when networkLink.Id is null; I generated a temporary Guid that's then used to remove the feature again.
