### ISSUE TITLE
Polygon extrude placing string/boolean value instead of bit value.

### ISSUE THREAD

**Issue by hashharvest** [samcragg/sharpkml#21]
Created a polygon as below:

`var polygon = new Polygon() { Extrude = false };`

Creates within a KML file with:

`<extrude>false</extrude>`

Expected behavior (as most validators expect a numeric bit value):

`<extrude>0</extrude>`

**Comment by samcragg** [comment]
Thanks for the bug report, however, the generated Kml is correct, as the specification states it's a `xsd:boolean` and even gives an example showing it as `false`

> 10.4.1.1.3 Content
> Type: xsd:boolean
> Default Value: 0 or false

For reference, the valid values for a boolean are `true`, `false`, `1`, `0` as per [W3C](https://www.w3.org/TR/xmlschema-2/#boolean) - perhaps raise an issue with the validator?
