### ISSUE TITLE
Unrecognized namespace

### ISSUE THREAD

**Issue by terribletim** [samcragg/sharpkml#24]
`kmlFile.Root` is null when attempting to load [USGS static kml - ColouredByAge](https://earthquake.usgs.gov/earthquakes/feed/v1.0/summary/1.0_week_age.kml)

It appears that namespace http://earth.google.com/kml/2.2 is not recognized. File will load if namespace is edited to "http://www.opengis.net/kml/2.2"

**Comment by samcragg** [comment]
Unfortunately the library is working as expected in this scenario, as the namespace is wrong. However there is another way to parse these files, see [LegacyFiles](https://github.com/samcragg/sharpkml/blob/master/docs/LegacyFiles.md) for an example.

I hope that helps.

**Comment by terribletim** [comment]
Thanks for info. It's a useful approach if you have the opportunity to inspect the file beforehand. But it's not suitable when trying to consume a web resource directly.
