### ISSUE TITLE
KmlFile.Load() cannot load some kml files " 'xsi' is an undeclared prefix. Line 82, position 34."

### ISSUE THREAD

**Issue by carroconnorC2IT** [samcragg/sharpkml#25]
KmlFile.Load(x) cannot load certain KML files. Looks like this may be due to a (new?) XML formatting issue that has a new namespace.

Here is part of the file that is causing this package some issues. It's caused on line 82, about 3/4 the way down. 

The exception returned says "'xsi' is an undeclared prefix. Line 82, position 34."

`<?xml version="1.0" encoding="UTF-8"?>
<kml xmlns="http://www.opengis.net/kml/2.2" xmlns:gx="http://www.google.com/kml/ext/2.2" xmlns:kml="http://www.opengis.net/kml/2.2" xmlns:atom="http://www.w3.org/2005/Atom">
<Document>
	<name>EDP Renewables.kml</name>
	<StyleMap id="msn_red-pushpin">
		<Pair>
			<key>normal</key>
			<styleUrl>#sn_red-pushpin</styleUrl>
		</Pair>
		<Pair>
			<key>highlight</key>
			<styleUrl>#sh_red-pushpin</styleUrl>
		</Pair>
	</StyleMap>
	<Style id="sh_red-pushpin">
		<IconStyle>
			<scale>1.3</scale>
			<Icon>
				<href>http://maps.google.com/mapfiles/kml/pushpin/red-pushpin.png</href>
			</Icon>
			<hotSpot x="20" y="2" xunits="pixels" yunits="pixels"/>
		</IconStyle>
		<BalloonStyle>
		</BalloonStyle>
		<ListStyle>
		</ListStyle>
	</Style>
	<Style id="sn_red-pushpin">
		<IconStyle>
			<scale>1.1</scale>
			<Icon>
				<href>http://maps.google.com/mapfiles/kml/pushpin/red-pushpin.png</href>
			</Icon>
			<hotSpot x="20" y="2" xunits="pixels" yunits="pixels"/>
		</IconStyle>
		<BalloonStyle>
		</BalloonStyle>
		<ListStyle>
		</ListStyle>
	</Style>
	<Style id="LineStyle00">
		<LabelStyle>
			<color>00000000</color>
			<scale>0</scale>
		</LabelStyle>
		<LineStyle>
			<color>ff0000aa</color>
			<width>2.5</width>
		</LineStyle>
		<PolyStyle>
			<color>00000000</color>
			<outline>0</outline>
		</PolyStyle>
	</Style>
	<Style id="LineStyle000">
		<LabelStyle>
			<color>00000000</color>
			<scale>0</scale>
		</LabelStyle>
		<LineStyle>
			<color>ff0000aa</color>
			<width>2.5</width>
		</LineStyle>
		<PolyStyle>
			<color>00000000</color>
			<outline>0</outline>
		</PolyStyle>
	</Style>
	<StyleMap id="LineStyle001">
		<Pair>
			<key>normal</key>
			<styleUrl>#LineStyle000</styleUrl>
		</Pair>
		<Pair>
			<key>highlight</key>
			<styleUrl>#LineStyle00</styleUrl>
		</Pair>
	</StyleMap>
	<Folder>
		<name>Temporary Places</name>
		<open>1</open>
		<Document id="ML1_AccessRoads" xsi:schemaLocation="http://www.opengis.net/kml/2.2 http://schemas.opengis.net/kml/2.2.0/ogckml22.xsd http://www.google.com/kml/ext/2.2 http://code.google.com/apis/kml/schema/kml22gx.xsd">
			<name>ML1_AccessRoads</name>
			<open>1</open>
			<Snippet maxLines="0"></Snippet>
			<StyleMap id="LineStyle002">
				<Pair>
					<key>normal</key>
					<styleUrl>#LineStyle003</styleUrl>
				</Pair>
				<Pair>
					<key>highlight</key>
					<styleUrl>#LineStyle005</styleUrl>
				</Pair>
			</StyleMap>
			<Style id="sh_red-pushpin0">
				<IconStyle>
					<scale>1.3</scale>
					<Icon>
						<href>http://maps.google.com/mapfiles/kml/pushpin/red-pushpin.png</href>
					</Icon>
					<hotSpot x="20" y="2" xunits="pixels" yunits="pixels"/>
				</IconStyle>
				<BalloonStyle>
				</BalloonStyle>
				<ListStyle>
				</ListStyle>
			</Style>
			<Style id="LineStyle003">
				<LabelStyle>
					<color>00000000</color>
					<scale>0</scale>
				</LabelStyle>
				<LineStyle>
					<color>ffff5500</color>
					<width>2.5</width>
				</LineStyle>
				<PolyStyle>
					<color>00000000</color>
					<outline>0</outline>
				</PolyStyle>
			</Style>`

**Comment by samcragg** [comment]
KML is a subset of XML, so the file parsed must be valid XML to start off with. Unfortunately, the `Document` element in there is causing problems:

    <Document id="ML1_AccessRoads" xsi:schemaLocation="http://www.opengis.net/kml/2.2 http://schemas.opengis.net/kml/2.2.0/ogckml22.xsd http://www.google.com/kml/ext/2.2 http://code.google.com/apis/kml/schema/kml22gx.xsd">

The error you're getting is because the `xsi:schemaLocation` is part of the `xsi` namespace, however, that namespace hasn't been declared. So you'll need to delcare it, perhaps on the top `kml` element:

    <kml ... xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">

If, however, you can't modify the source of the KML, there is another option to parse it ignoring namespaces:

    var parser = new Parser();
    parser.Parse(fileStream, namespaces: false); // or ParseString("...", false)
    var kml = (Kml)parser.Root;

Hope that helps and thanks for using the library 🙂

**Comment by bfmyr4** [comment]
What if you are using KmzFile.Open(stream).GetDefaultKmlFile() or KmlFile.Load(stream)?
