### ISSUE TITLE
kml format is not supported

### ISSUE THREAD

**Issue by antonad** [samcragg/sharpkml#27]
Hello.
I have tried to use SharpKml for parsing this file.
There are 2 problems while parsing:
1. import fails until I have removed kml tag and replaced Document with Document xmlns="http://www.opengis.net/kml/2.2"

2. because of tabs in text file styles was parsed with bugs, for example color = ddff0000  was parsed as 0000000d

[Geofences.zip](https://github.com/samcragg/sharpkml/files/4297638/Geofences.zip)

Can you comment first problem? Can <Document> without xmlns be used? Can <xml> be used?

Can you remove /tabs, blanks before parsing colors and similar fields?

Thanks.

**Comment by samcragg** [comment]
For the first problem you can use the `Parser` directly to ignore namespaces, see [legacy files](https://github.com/samcragg/sharpkml/blob/master/docs/LegacyFiles.md) for an example.

For the second problem, I've just publised an updated package (v 5.1.1) that will now ignore the whitespace, sorry about that.

Thanks for opening the issue; if there are any other errors then please feel free to open a new one 🙂

**Comment by antonad** [comment]
Thank you very much.
Working great.
