### ISSUE TITLE
Google kml files not opened

### ISSUE THREAD

**Issue by ahvahsky2008** [samcragg/sharpkml#35]
I try read my kml file, but results empty. Why so?

[doc.zip](https://github.com/samcragg/sharpkml/files/5646891/doc.zip)

```
using (TextReader reader = File.OpenText("doc.kml"))
{
 var re = reader.ReadToEnd();
 KmlFile file = KmlFile.Load(reader);
}
```

**Comment by samcragg** [comment]
I think the problem is that you've called `ReadToEnd` on the reader, which advances it to the end of the stream. Once you pass that reader to the `Load` method, there is nothing left for it to read from the reader. Perhaps you could try this instead:

```c#
KmlFile file = KmlFile.Load(File.Open("doc.kml"));
```

Hope that helps
