### ISSUE TITLE
RemoveFeature needs an Id

### ISSUE THREAD

**Issue by xanatos** [samcragg/sharpkml#38]
See this question on SO: https://stackoverflow.com/questions/65539123/delete-a-placemark-and-save-the-whole-kml-minus-the-placemark-into-a-new-file/65541208

The `Folder.RemoveFeature()` uses the `id` as the key. But from what I've observed for example in the official [Google sample file](https://developers.google.com/kml/documentation/KML_Samples.kml), `Id` are optional. You should add an overload `Folder.RemoveFeature(Feature feature)`.

**Comment by samcragg** [comment]
Thanks for reporting that (and answering the SO question).

I've created 5.2.0 that has the overload (and fixed some of the examples using `OpenWrite` - if you know of any other improvements then please feel free to raise an issue/PR to help improve the library)

Thanks again 🙂
