### ISSUE TITLE
KmlFile.Load returns empty file

### ISSUE THREAD

**Issue by dissymmetryoflift** [samcragg/sharpkml#41]
Update below

**Comment by dissymmetryoflift** [comment]
Any idea how I would parse the attached KML? QGIS and other GIS software suites seem to have no issue.

`<?xml version="1.0" encoding="UTF-8"?>
<kml xmlns="http://earth.google.com/kml/2.1">
  <Document>
    <name>test kml document</name>
    <Placemark>
      <Style>
        <IconStyle>
          <heading>0</heading>
          <Icon>
            <href>http://maps.google.com/mapfiles/kml/shapes/donut.png</href>
          </Icon>
          <color>ff0101fe</color>
        </IconStyle>
      </Style>
      <name>19-2858 / 3410.4331 ft</name>
      <description>&lt;hr&gt;&lt;table width='550'&gt;&lt;tr&gt;&lt;td width='50%'&gt;&lt;b&gt;File No / N° du fichier :&lt;/b&gt;&lt;/td&gt;&lt;td&gt;19-2858&lt;/td&gt;&lt;/tr&gt;&lt;tr&gt;&lt;td width='50%'&gt;&lt;b&gt;Location / Emplacement :&lt;/b&gt;&lt;/td&gt;&lt;td&gt;Cynthia, AB&lt;/td&gt;&lt;/tr&gt;&lt;tr&gt;&lt;td width='50%'&gt;&lt;b&gt;LAT (N) / N (LAT) :&lt;/b&gt;&lt;/td&gt;&lt;td&gt;53° 11' 19.51"&lt;/td&gt;&lt;/tr&gt;&lt;tr&gt;&lt;td width='50%'&gt;&lt;b&gt;LONG (W) / W (LONG) :&lt;/b&gt;&lt;/td&gt;&lt;td&gt;115° 38' 09.75"&lt;/td&gt;&lt;/tr&gt;&lt;tr&gt;&lt;td width='50%'&gt;&lt;b&gt;Ground (ft) / Sol (pi) :&lt;/b&gt;&lt;/td&gt;&lt;td&gt;3310.3675&lt;/td&gt;&lt;/tr&gt;&lt;tr&gt;&lt;td width='50%'&gt;&lt;b&gt;Height AGL (ft) / Hauteur AGL (pi) :&lt;/b&gt;&lt;/td&gt;&lt;td&gt;100.0656&lt;/td&gt;&lt;/tr&gt;&lt;tr&gt;&lt;td width='50%'&gt;&lt;b&gt;Total Elevation (ft) / Hauteur total (pi) :&lt;/b&gt;&lt;/td&gt;&lt;td&gt;3410.4331&lt;/td&gt;&lt;/tr&gt;&lt;tr&gt;&lt;td width='50%'&gt;&lt;b&gt;Land Use Type / Type d'utilisation de terrains :&lt;/b&gt;&lt;/td&gt;&lt;td&gt;Communication / Communication&lt;/td&gt;&lt;/tr&gt;&lt;tr&gt;&lt;td width='50%'&gt;&lt;b&gt;Description / Description :&lt;/b&gt;&lt;/td&gt;&lt;td&gt;Self-support Tower / Tour autoportante&lt;/td&gt;&lt;/tr&gt;&lt;tr&gt;&lt;td width='50%'&gt;&lt;b&gt;Notification Type / Type d'avis :&lt;/b&gt;&lt;/td&gt;&lt;td&gt;NOR / NOR&lt;/td&gt;&lt;/tr&gt;&lt;tr&gt;&lt;td width='50%'&gt;&lt;b&gt;Multiple Obstacles / Obstacles Multiples :&lt;/b&gt;&lt;/td&gt;&lt;td&gt;No / Non&lt;/td&gt;&lt;/tr&gt;&lt;/table&gt;</description>
      <visibility>1</visibility>
      <Point>
        <coordinates>-115.6360416667,53.1887527778,1009.000014</coordinates>
        <altitudeMode>clampToGround</altitudeMode>
        <extrude>1</extrude>
      </Point>
    </Placemark>
  </Document>
</kml>
`

**Comment by samcragg** [comment]
Sorry, didn't see this. As it's been a while I'm going to close this issue but if you have a specific question about a feature then feel free to create a new one.
