### ISSUE TITLE
KmzFile.Create(kml) error looking for System.IO.Compression, Version=4.2.0.0

### ISSUE THREAD

**Issue by fabrizioPucci** [samcragg/sharpkml#42]
A call to **KmzFile.Create(kml)** return the error for looking at System.IO.Compression, Version=4.2.0.0

It worked in the past but now I have a new PC and I have installed only Visual Studio 2022 (64 bit) 17.0.4 (no precedent version of visual studio are installed) and now it includes only "SistemIO.Compression 4.3.0" but the assembly selection shows only 
System.IO.Compression, Version=4.2.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089

I tried to downgrade the SistemIO.Compression in Nuget console but the only versions are 4.1 and 4.3.
How can I fix it?
thank you

If I create a simple project from scratch it works, 
but in my project I receive this error:

Exception:
System.IO.FileNotFoundException: 'Non è stato possibile caricare il file o l'assembly 'System.IO.Compression, Version=**4.2.0.0**, Culture=neutral, PublicKeyToken=b77a5c561934e089' o una delle relative dipendenze. Impossibile trovare il file specificato.'

Internal Exception:
FileNotFoundException: Non è stato possibile caricare il file o l'assembly 'System.IO.Compression, Version=**4.0.0.0**, Culture=neutral, PublicKeyToken=b77a5c561934e089' o una delle relative dipendenze. Impossibile trovare il file specificato.

**Comment by samcragg** [comment]
Sorry, unable to replicate this. Please feel free to reopen the issue if it's still a problem.
