### ISSUE TITLE
Can't add styleUrl because of its Uri type

### ISSUE THREAD

**Issue by moojek** [samcragg/sharpkml#45]
Hi,
currently StyleUrl in Feature.cs is of type Uri. KML Reference states though, that you can use "#styleName" for styles located in the same file (https://developers.google.com/kml/documentation/kml_tut#geometrystyles), but it's unusable here because "#styleName" is not valid Uri.

**Comment by Krzysztofz01** [comment]
You can pass the id using relative URI. Example:
```csharp
exampleElement.StyleUrl = new Uri("#myCustomId", UriKind.Relative);
```

**Comment by moojek** [comment]
Oh, I didn't know you can do that. That seems to work then, thanks.
