### ISSUE TITLE
Coordinate collection does not handle 'NaN' values for altitude component

### ISSUE THREAD

**Issue by hf-farmqa** [samcragg/sharpkml#48]
Some tooling will write out KML placemark feature geometries with the altitude component being set to NaN rather than have it omitted. This leads to issues when resolving the coordinate collection during parsing.

Assuming that I'm reading the source correctly, this probably could be fix by either slapping in something to check for the text NaN either in CoordinateCollection.cs:Parse() to ignore altitude in that case or within DecimalDegree.cs to support parsing into valid double.NaN.

Without this change we are forced with pre-processing the files and ripping out NaN values prior to passing them to SharpKml (and hoping our regex is targeted well enough)

**Comment by hf-farmqa** [comment]
For my issue it is the second case you've listed, where the altitude component of the coordinate is set to NaN. (or rather 'nan' to needlessly mention case insensitivity)

'All input is evil' as the old saying goes.

Thanks for talking a look

**Comment by samcragg** [comment]
That should be fixed now in the latest release - feel free to reopen though if that's not the case.
