### ISSUE TITLE
Unable to get Values from gx:SimpleArrayData

### ISSUE THREAD

**Issue by flyer299** [samcragg/sharpkml#5]
I am trying to get access to values in <ExtendedData><SchemaData>...  My Test Console App returns the word "Value" instead of what is in the Value Node.

Examples are included:

Sample Code:
`using SharpKml.Dom;
using SharpKml.Engine;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace KMLTest
{
    class KMLTestApp
    {
        private const string InputFile = "Sample.kml";
        static void Main(string[] args)
        {
            using (StreamReader kmlStream = new StreamReader(InputFile))
            {

                KmlFile file = KmlFile.Load(kmlStream);
                if (file == null)
                {
                    return;
                }

                // It's good practice for the root element of the file to be a Kml element
                Kml kml = file.Root as Kml;
                if (kml != null)
                {
                    List<Placemark> placemarks = new List<Placemark>();
                    ExtractPlacemarks(kml.Feature, placemarks);

                    // Sort using their names
                    placemarks.Sort((a, b) => string.Compare(a.Name, b.Name));

                    // Display the results
                    foreach (var placemark in placemarks)
                    {
                        Console.WriteLine("Placemark: {0}", placemark.Name);
                    }
                }
            }
            Console.WriteLine("Press Enter to Exit");
            var input = Console.ReadLine();
        }

        private static void ExtractPlacemarks(Feature feature, List<Placemark> placemarks)
        {
            // Is the passed in value a Placemark?
            Placemark placemark = feature as Placemark;
            if (placemark != null)
            {
                placemarks.Add(placemark);
            }
            else
            {
                // Is it a Container, as the Container might have a child Placemark?
                Container container = feature as Container;
                if (container != null)
                {
                    Console.WriteLine("Found Container: {0}", container.Name);
                    // Check each Feature to see if it's a Placemark or another Container
                    foreach (var f in container.Features)
                    {
                        ExtractPlacemarks(f, placemarks);
                    }

                    foreach(var data in container.ExtendedData.Data)
                    {
                        Console.WriteLine("Extended Data: {0}", data.Name);
                    }

                    foreach (var data in container.ExtendedData.SchemaData)
                    {
                        foreach(var item in data.GXSimpleArray)
                        {
                            Console.WriteLine("gxSimpleArray: {0}", item.Name);
                            foreach (var value in item.Values) {
                                //This Returns "Value" and should return the value stroed in the SimpleArrayData Element
                                Console.WriteLine("Value {0}", value.ToString());
                            }
                        }
                        
                    }

                }
                else
                {
                    Console.WriteLine("Other: {0}", feature.Name);
                }
            }
        }
    }
}
`

Sample KML File
`<?xml version="1.0" encoding="UTF-8"?>
<kml xmlns="http://www.opengis.net/kml/2.2"  xmlns:gx="http://www.google.com/kml/ext/2.2">
    <Document>
        <open>1</open>
        <visibility>1</visibility>

        <Style id="trackStyle">
            <LineStyle>
                <color>ffDB9034</color>
                <width>4</width>
            </LineStyle>
            <PolyStyle>
                <color>80DB9034</color>
            </PolyStyle>
        </Style>
        <Style id="pathStyle">
            <LineStyle>
                <color>f8000080</color>
                <width>8</width>
            </LineStyle>
        </Style>
        <Placemark>
            <name></name>
            <styleUrl>#trackStyle</styleUrl>
            <gx:Track>
                <altitudeMode>absolute</altitudeMode>
                <extrude>1</extrude>
                <altitudeMode>absolute</altitudeMode>
                <gx:interpolate>1</gx:interpolate>
                
                <when>2018-02-12T00:39:20.71Z</when>
                <gx:coord>-97.678726 30.674970 225.0</gx:coord>
                
                <when>2018-02-12T00:39:21.34Z</when>
                <gx:coord>-97.678713 30.675155 225.0</gx:coord>
                
                <when>2018-02-12T00:39:22.11Z</when>
                <gx:coord>-97.678695 30.675410 225.0</gx:coord>
                
                 </gx:Track>
        </Placemark>
        <Placemark>
            <name>Start</name>
            <Point>
                <coordinates>-97.678726,30.674970,225.0</coordinates>
            </Point>
        </Placemark>
        <ExtendedData>
            <SchemaData>
                <gx:SimpleArrayData name="acc_horiz">
                    
                    <gx:value>0</gx:value>
                    
                    <gx:value>0</gx:value>
                    
                    <gx:value>0</gx:value>
                    
                </gx:SimpleArrayData>
                <gx:SimpleArrayData name="course">
                    
                    <gx:value>3.64</gx:value>
                    
                    <gx:value>3.61</gx:value>
                    
                </gx:SimpleArrayData>
                <gx:SimpleArrayData name="altitude">
                    
                    <gx:value>738.19</gx:value>
                    
                    <gx:value>738.19</gx:value>
                    
                    <gx:value>738.19</gx:value>
                    
                </gx:SimpleArrayData>
                <gx:SimpleArrayData name="bank">
                    
                    <gx:value>-1.40</gx:value>
                    
                    <gx:value>-1.15</gx:value>
                    
                    <gx:value>-1.08</gx:value>
                    
                </gx:SimpleArrayData>
                <gx:SimpleArrayData name="pitch">
                    
                    <gx:value>-2.22</gx:value>
                    
                    <gx:value>-2.98</gx:value>
                    
                    <gx:value>-3.12</gx:value>
                                     
                </gx:SimpleArrayData>
            </SchemaData>
            <Data name="source">
                <displayName>Source</displayName>
                <value>ForeFlight Mobile</value>
            </Data>
            <Data name="GPSModelName">
                <value>Stratus</value>
            </Data>
            <Data name="flightTitle">
                <value>KGTU - KAUS</value>
            </Data>
            <Data name="pilotName">
                <value></value>
            </Data>
            <Data name="tailNumber">
                <value>N111CV</value>
            </Data>
            <Data name="pilotNotes">
                <value></value>
            </Data>
            <Data name="routeWaypoints">
                <displayName>Route</displayName>
                <value>KAQO KAUS</value>
            </Data>
        </ExtendedData>
    </Document>
</kml>

`

**Comment by samcragg** [comment]
Thanks for using the library and for reporting that.

I've fixed that in version 3.0.3, which is available on NuGet now.

Please re-open if you still have any problems.
