### ISSUE TITLE
Support for .NET 4.5

### ISSUE THREAD

**Issue by crowbarsolutions** [samcragg/sharpkml#6]
Seems that the latest nuget package forces the .NET Standard libraries as a dependency. Any plans of adding a .NET 4.5 dependency branch or creating a legacy package that supports .NET 4.5?

**Comment by samcragg** [comment]
I've updated the NuGet package now (3.0.4) so it supports 4.5, as .NET Standard only support 4.5.1 onwards

Let me know if there are any problems
